### ISSUE TITLE
proxy wont work

### ISSUE THREAD

**Issue by nickaein-a** [blackarrowsec/mssqlproxy#1]
everything seems fine, but everytime i try to use the proxy, it throws exception.

```
Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

mssqlproxy - Copyright 2020 BlackArrow
Password:
[*] Encryption required, switching to TLS
[*] ENVCHANGE(DATABASE): Old Value: master, New Value: master
[*] ENVCHANGE(LANGUAGE): Old Value: None, New Value: us_english
[*] ENVCHANGE(PACKETSIZE): Old Value: 4096, New Value: 16192
[*] INFO(SERVER): Line 1: Changed database context to 'master'.
[*] INFO(SERVER): Line 1: Changed language setting to us_english.
[*] ACK: Result: 1 - Microsoft SQL Server   (140 11221)
[*] Proxy mode: check
[*] Assembly is installed
[*] Procedure is installed
[*] reciclador is installed
[*] clr enabled
[*] Proxy mode: start
[*] Listening on port 2080...
[*] ACK from server!
[*] New connection
Unhandled exception in thread started by <function proxy_worker at 0x0000000004889F28>Unhandled exception in thread started by <function proxy_worker at 0x0000000004889F28>
Traceback (most recent call last):

Traceback (most recent call last):
  File "mssqlclient.py", line 174, in proxy_worker
  File "mssqlclient.py", line 174, in proxy_worker
        data = client.recv(2048)
data = client.recv(2048)
socket.errorsocket.error: [Errno 10054] An existing connection was forcibly closed by the remote host
: [Errno 10054] An existing connection was forcibly closed by the remote host

```

**Comment by xassiz** [comment]
Hi! Can you tell how you are connecting to the proxy?

Btw, have you modified the code? Line 174 shouldn't correspond with that recv...

**Comment by nickaein-a** [comment]
I tried proxifier and IE Proxy settings
Is it socks5?

Yes i added some print function for debugging

**Comment by xassiz** [comment]
Yes, it's socks5, I forgot to mention in the README (https://www.blackarrow.net/mssqlproxy-pivoting-clr/). For the moment it only supports IPv4 and no domain names, I don't if this is your case.

I only tried it with [proxychains-ng](https://github.com/rofl0r/proxychains-ng).

**Comment by nickaein-a** [comment]
i was using chrome for testing, it made too many http requests and i think somehow it was problematic.
and also i used your released library this time. 
now it works like a charm
thank you for your time

**Comment by xassiz** [comment]
Np, glad it worked! Closing this issue.
